# Literature Review

## Overview

Researchers acknowledge that there exists uncertainty in transportation demand models, though few choose to quantify it. This review looks at the types of uncertainty that exists, and research that has been done to evaluate uncertainty. Then, this review considers methods for value sampling, which has been used in research to create a range of input values or parameters.

## Types of Uncertainty

Uncertainty generally exists from two basic sources: input uncertainty and model uncertainty [@rasouli2012uncertainty]. Input uncertainty includes behavioral and socioeconomic data – for instance, the number of jobs and residents in a zone might be coded incorrectly – as well as parameter estimates including automobile operating costs, gasoline costs, and values of time. Model uncertainty can be further divided into specification error and estimation error. Specification error is a failure to estimate the “true” model. Estimation error, on the other hand, is a failure to estimate the correct values of model constants and parameters, or taking the mean estimated value as a single parameter. 

### Input Uncertainty

### Model Uncertainty

## Sampling Methods

There are two popular methods of value sampling, Monte Carlo simulation and Latin hypercube sampling. Monte Carlo simulation draws independently from multiple distributions, while Latin hypercube sampling makes draws that cover the parameter space more efficiently and can capture the joint distribution between two or more parameter values. As a result, Latin hypercube sampling can reduce the number of draws needed to fully re-create the statistical variance in a model, but the amount of reduction is unknown and may not be universal to all problems [@yang2013sensitivity].

## Summary

In a four-step travel demand model, most error research to this point has focused on input uncertainty, rather than model uncertainty [@rasouli2012uncertainty]. For this study, the estimation error within the model uncertainty is of the most immediate concern.