# Conclusions

The uncertainty and variance present in the model results are overall smaller than the variability introduced to the model through the parameters. Auto trips have less variance than transit or non-motorized trips, regardless of the number of trips in a given zone. When there is only two modes available auto trips have even lower variance. Higher volume roads have greater certainty than lower volume ones. Also, uncertainty that exists within the first three steps of the model appears to be corrected by the limitations of the highway network assignment. Overall there is a variance of approximately 1% in the model outputs, when a 10 percent variance was used for the parameter estimates.

In general, this research has shown that statistical parameter uncertainty does not appear to be a significant factor in forecasting traffic volumes using transportation demand models. The result uncertainty is generally equally to or smaller than the input parameter variance. The uncertainty in parameter inputs appears to lead to variation in highway volumes that is lower than the error between the model forecast and the highway counts. Any variation in mode and destination choice probabilities appears to be constrained by the limitations of the highway network assignment.

There are several limitations that must be mentioned in this research, however. First, I did not attempt to address the statistical uncertainty in trip rate estimates; these may play a substantially larger role than destination and mode choice parameters, given that lower trip rates may lead to lower traffic volumes globally, which could not be “corrected” by the static user equilibrium assignment. And the assignment itself might have been aided in this case by the RVTPO’s relatively simplistic highway network: if only two major highways exist the number of realistic lowest cost path choices between regions is somewhat constrained. It may be that in a larger network with more path redundancies, the assignment may not have been as helpful in constraining the forecasted volumes.

In this research I had only the estimates of the statistical coefficients, and therefore had to assume a coefficient of variation to derive variation in the sampling procedure. It would be better if model user and development documentation more regularly provided estimates of the standard errors of model parameters. Even better would be variance-covariance matrices for the estimated models, enabling researchers to ensure that covariance relationships between sampled parameters are maintained.

Notwithstanding these limitations, statistical parameter variance is not likely the largest source of uncertainty in travel forecasting. There are likely more important factors at play that planners and government agencies should address. Research on all sources of uncertainty is somewhat limited, but in many ways has been hampered by the burdensome computational requirements of many modern travel models [@voulgaris2019crystal]. This research methodology benefited from a lightweight travel model that could be repeatedly re-run with dozens of resampled choice parameters. Better understanding the other sources of uncertainty -- model specification and input accuracy -- might also benefit from lightweight models constructed for transparency and flexibility rather than heavily constrained models emphasizing precise spatial detail and strict behavioral constraints. This might allow forecasts to be made with an ensemble approach [@wu2021ensemble], identifying preferred policies as the consensus of multiple plausible model specifications.